### ISSUE TITLE
Map Record selection

### ISSUE THREAD

**Issue by Towermonger** [coolkang/pwaaweb#13]
When selecting polygons on the map the result panel is not repopulating. 
Experienced this issue in both Google Chrome and Mozilla Firefox.

**Comment by coolkang** [comment]
This issue was caused by shifting map area to left when a result panel is opened. So, the coordinate of the map is not reflected correctly on mouse click. This item will be fixed when a result panel is open overlaying the page without pushing the map to left. This will be fixed when issue #14 Map Resizing is implemented.

**Comment by coolkang** [comment]
Ian,

Please test this. We fixed this issue by not-shifting UI to the left and now it should work fine.

**Comment by Towermonger** [comment]
Tested, no issues found.
